permalink: pretty

sass:
  style: :compressed

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

baseurl: "http://klokantech.github.io/www.iiifserver.com/"
