name: IIIFServer

permalink: pretty

sass:
  style: :compressed
  sass_dir: styles/_sass
  
exclude:
  - styles/base.scss

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

baseurl: "/"
